name: Release PHP

on:
  push:
    branches: [release/*]

jobs:
  publish-php-subrepo:
    name: Publish to cucumber/gherkin-php subrepo
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: '0'
      - uses: cucumber/action-publish-subrepo@29cdfead1117bb466d1f2de20fc2c86a3c02e93f # v1.1.1
        with:
          working-directory: php
          github-token: ${{ secrets.CUKEBOT_GITHUB_TOKEN }}
