name: Release Perl/CPAN

on:
  push:
    branches: [release/*]

jobs:
  create-perl-release:
    name: Publish to CPAN
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cucumber/action-publish-cpan@c9880d2be084deb71772a014135b60fe463c364d # v1.0.1
        with:
          cpan-user: ${{ secrets.CPAN_USER }}
          cpan-password: ${{ secrets.CPAN_PASSWORD }}
          working-directory: 'perl'
